SLOT_TYPE = [
    ('Integer', '数值'),
    ('Float', '小数'),
    ('Text', '文本'),
    ('Enum', '枚举'),
    ('Date', '日期'),
    ('DateTime', '日期时间'),
    ('Time', '时间'),
    ('TimeInterval', '时间区间'),
    ('URL', '地址'),
    ('Price', '价格'),
    ('Country', '国家'),
    ('City', '城市'),
    ('Person', '人名'),
    ('Org', '机构名'),
    ('AirPort', '机场'),
    ('Phone', '电话号码'),
    ('Software', '软件'),
    ('Unit', '单位'),
]
